<?php

namespace App\Console\Commands;

use Illuminate\Filesystem\Filesystem;
use Illuminate\Foundation\Console\ModelMakeCommand as Command;

class ModelMakeCommand extends Command
{
    use MaxDevRoot;

    public $Dir = 'Models';

    public function handle()
    {
//        dd($this->getDefaultNamespace($this->rootNamespace()).'\\'.$this->getNameInput());
        return parent::handle(); // TODO: Change the autogenerated stub

        $this->runCommand('php artisan ide-helper:models', [$this->getDefaultNamespace($this->rootNamespace()).'\\'.$this->getNameInput()]);
    }
}
